- assert:
    that:
     - "docker_hub_host is defined"
     - "docker_hub_username is defined"
     - "docker_hub_password is defined"

- name: Log into {{ docker_hub_host }} registry
  docker_login:
    registry: "{{ docker_hub_host }}"
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
    reauthorize: "{{ docker_hub_reauthorize }}"
