- name: Update sources list
  apt: update_cache=yes cache_valid_time=3600

- name: Install apt-transport-https
  apt: name=apt-transport-https

- name: Install ca-certificates
  apt: name=ca-certificates

- name: Add Docker repository key
  apt_key:
    id: "{{ docker_repo_key_sig }}"
    url: "{{ docker_repo_key_url }}"
    state: present

- name: Add deb repo docker
  apt_repository: repo="{{ docker_repo_deb }}"

- name: Update sources list
  apt: update_cache=yes

- name: Install docker
  apt: name=docker-ce

- name: Started docker
  service: name=docker state=started

- name: Install pip
  apt: name=python-pip

- name: Update pip
  pip: name=pip state=latest

- name: Install docker for python
  pip:
    name: docker

- name: Setup Docker compose binary
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_bin }}"
    owner: root
    group: root
    mode: 0755
    checksum: "{{ docker_compose_checksum }}"
