- name: Update sources list
  apt: update_cache=yes cache_valid_time=3600

- name: Install apt-transport-https
  apt: name=apt-transport-https

- name: Install ca-certificates
  apt: name=ca-certificates

- name: Install pip
  apt: name=python-pip

- name: Update pip
  pip: name=pip state=latest

- name: Add Docker repository key
  apt_key:
    id: "{{ docker_repo_key_sig }}"
    url: "{{ docker_repo_key_url }}"
    state: present

- name: Add deb repo docker
  apt_repository: repo="{{ docker_repo_deb }}"

- name: Update sources list
  apt: update_cache=yes

- name: Install docker
  apt: name=docker-ce

- name: Started docker
  service: name=docker state=started

- name: Install docker for python
  pip:
    name: docker

- name: Install Docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"

- name: Install Docker ctop
  get_url:
    url: "https://github.com/bcicen/ctop/releases/download/v{{ docker_ctop_version }}/ctop-{{ docker_ctop_version }}-linux-amd64"
    dest: /usr/local/bin/ctop
    mode: 0755
    checksum: "{{ docker_ctop_checksum }}"
