- name: Update sources list
  apt: update_cache=yes cache_valid_time=3600

- name: Install apt-transport-https
  apt: name=apt-transport-https

- name: Install ca-certificates
  apt: name=ca-certificates

- name: Install curl
  apt: name=curl

- name: Install gnupg-agent
  apt: name=gnupg-agent

- name: Install software-properties-common
  apt: name=software-properties-common

- name: Add Docker repository key
  apt_key:
    id: "{{ docker_repo_key_sig }}"
    url: "{{ docker_repo_key_url }}"
    state: present

- name: Add deb repo docker
  apt_repository: repo="{{ docker_repo_deb }}"

- name: Update sources list
  apt: update_cache=yes

- name: Install docker
  apt: name=docker-ce

- name: Started docker
  service: name=docker state=started

- name: Generate Docker config
  template:
    src: "{{ docker_config_template }}"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0744
  when:
    - docker_config_use
  notify:
    - restart docker

- name: Setup Docker compose binary
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_bin }}"
    owner: root
    group: root
    mode: 0755
    checksum: "{{ docker_compose_checksum }}"
